networks:
  network7:
    name: network7

services:
  nginx7:
    container_name: nginx7
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network7
    depends_on:
      - php7
      - mysql7

  php7:
    container_name: php7
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network7
    depends_on:
      - mysql7

  mysql7:
    container_name: mysql7
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network7

  phpmyadmin7:
    container_name: phpmyadmin7
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql7
    networks:
      - network7
    depends_on:
      - mysql7